ALTER TABLE treasure_item DROP COLUMN IF EXISTS dynasty;
ALTER TABLE treasure_item DROP COLUMN IF EXISTS mint_uncertain;
ALTER TABLE treasure_item ADD COLUMN IF NOT EXISTS epoch INTEGER REFERENCES epoch(id);
ALTER TABLE treasure_item ADD COLUMN IF NOT EXISTS reconstructed BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE treasure_item ADD COLUMN IF NOT EXISTS mint_region_uncertain BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE treasure_item ADD COLUMN IF NOT EXISTS mint_as_on_coin TEXT;