ALTER TABLE treasure_item DROP COLUMN IF EXISTS mint;
ALTER TABLE treasure_item DROP COLUMN IF EXISTS mint_area;


DROP TABLE IF EXISTS mint_area;
CREATE TABLE IF NOT EXISTS mint_area (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    location GEOMETRY,
    uncertain BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE treasure_item ADD COLUMN IF NOT EXISTS mint_area INTEGER REFERENCES mint_area(id) ON DELETE RESTRICT ON UPDATE CASCADE;


 